version: "3.8"

services:
  parseinvoice:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile.parseinvoice  # Use your FastAPI server's Dockerfile
    image: parseinvoice:latest  # Name the built image
    container_name: parseinvoice
    restart: always
    depends_on:
      - invoice2data  # Ensure invoice2data starts first
    volumes:
      - ./data/templates:/app/data/templates
      - ./data/pdfs:/app/data/pdfs
      - ./data/output:/app/data/output
      - ./data/invoices.db:/app/data/invoices.db  # Persist SQLite database
    ports:
      - "8000:8000"  # Expose FastAPI server
    networks:
      - invoice_network

  invoice2data:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile  # Use the invoice2data Dockerfile
    image: invoice2data:latest  # Name the built image
    container_name: invoice2data
    restart: always
    volumes:
      - ./data/templates:/app/data/templates
      - ./data/pdfs:/app/data/pdfs
      - ./data/output:/app/data/output
    command: tail -f /dev/null  # Keeps the container running for debugging
    networks:
      - invoice_network

networks:
  invoice_network:
    driver: bridge
